### ISSUE TITLE
Versions 1.5, 1.6 and 1.7.1 do not work. Is there a confirmed working version of this action?

### ISSUE THREAD

**Issue by leinardi** [fundacaocerti/mobsf-action#15]
I'm trying to use this action but it just doesn't work. All versions I tried fail for a reason or another.
Version 1.5 [fails](https://github.com/leinardi/Forlago/runs/4991362350?check_suite_focus=true#step:2:183) with this error:
```
  Reading package lists...
  E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
  The command '/bin/sh -c apt-get update -y &&   apt-get install -y curl jq' returned a non-zero code: 100
  
Error: Docker build failed with exit code 100
```
Version 1.6 [fails](https://github.com/leinardi/Forlago/runs/4991375145?check_suite_focus=true#step:2:183) with this error:
```
  Reading package lists...
  E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
  The command '/bin/sh -c apt-get update -y &&   apt-get install -y curl jq' returned a non-zero code: 100
  
Error: Docker build failed with exit code 100
```
Version 1.7.1 [fails](https://github.com/leinardi/Forlago/runs/4991330190?check_suite_focus=true#step:11:21) with this error:
```
[2022-01-29 13:20:19 +0000] [15] [INFO] Booting worker with pid: 15
Creating MobSF Home Directory
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/init.py", line 111, in get_mobsf_home
    os.makedirs(mobsf_home)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/github/home/.MobSF'
Error: 1-29 13:20:19 +0000] [15] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
```
The workflow code is available here:
https://github.com/leinardi/Forlago/blob/master/.github/workflows/mobsf.yml

**Comment by leinardi** [comment]
Related to #14

**Comment by leinardi** [comment]
@inm-certi please check here: When using local mounts, you need to set appropriate permissions. The fix needs to be implemented in the action.

**Comment by jpeiffer** [comment]
I don't think that there is a "one size fits all" approach.  Unfortunately, because the Dockerfile was switched to user space rather than root on MobSF's side, the user has to be assigned the appropriate permissions on the host computer, and the Docker side of things (this action) has no way of knowing the host volumes to assign the permissions to.

It's not a lost cause though...  If you're using the built in Linux runners on GitHub, add this block before your invocation of the action and it should work:
```
      - run: |
          sudo mkdir -p /home/runner/work/_temp/_github_home
          sudo chown -R 9901:9901 /home/runner/work/_temp/_github_home

          sudo mkdir -p /home/runner/work/$myRepoName/$myRepoName
          sudo chown -R 9901:9901 /home/runner/work/$myRepoName/$myRepoName
```

The `9091` is the uid and gid used for the user inside of mobsf's runner.

The even more fun part is `$myRepoName` needs to be the name of your repo.  I'm sure you can get that from some env var already, but I've been at this for hours... and I'm tired.  :)

If you have your own runners though, you will have to dig in and find the appropriate paths to add.

**Comment by leinardi** [comment]
Hey @jpeiffer thanks! This works like a charm!

BTW, I found a way to get the repo so that doesn't have to be hardcoded:

```yaml
      - run: |
          sudo mkdir -p /home/runner/work/_temp/_github_home
          sudo chown -R 9901:9901 /home/runner/work/_temp/_github_home

          sudo mkdir -p /home/runner/work/$REPO_NAME/$REPO_NAME
          sudo chown -R 9901:9901 /home/runner/work/$REPO_NAME/$REPO_NAME
        env:
          REPO_NAME: ${{ github.event.repository.name }}
```

**Comment by jpeiffer** [comment]
Awesome.  I noticed that it also creates a warning about not being able to clean up something from the action with this (and my original) fix.

I had to add this after the step that runs MobSF to clear that warning:
```
      - name: Complete for MobSF
        run: |
          set -e

          sudo chown -R runner:docker /home/runner/work/_temp/_github_home
          sudo chown -R runner:docker /home/runner/work/$REPO_NAME/$REPO_NAME
```

That changes the permissions back on the folders so the cleanup steps can successfully complete.

**Comment by leinardi** [comment]
Thanks! I can confirm that this fixes the cleanup warning.
Just out of curiosity: why is the `set -e` needed? Is it just to prevent running the second chmod in case the first fails?
What would be the worst thing that could happen if it's removed?

**Comment by jpeiffer** [comment]
Honestly... it's just habit.  :)

Whenever I do shell scripts in actions I use `set -e` as the first line so that the block fails if any part fails and if part of the script is allowed to fail while continuing, I explicitly put `set +e` in there.  It's just to be explicit in my intentions.

**Comment by inm-certi** [comment]
@jpeiffer, @leinardi,  Can you review this PR? https://github.com/fundacaocerti/mobsf-action/pull/16

I can't test right now and I'm not sure if is this the right solution.
